# Generated by Django 5.0.3 on 2024-03-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author_email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='message',
            name='author_name',
            field=models.CharField(max_length=50, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_posted',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.IntegerField(verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.TextField(verbose_name='Сообщение'),
        ),
    ]
