# Generated by Django 5.0.3 on 2024-06-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_message_author_email_alter_message_author_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_id',
        ),
        migrations.AlterField(
            model_name='message',
            name='date_posted',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата публикации'),
        ),
    ]
